name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew lintKotlin
      - run: ./gradlew lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew yorkie:testDebugUnitTest
      - run: ./gradlew yorkie:jacocoDebugTestReport
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-artifact
          path: yorkie/build/reports/jacoco/jacocoDebugTestReport/jacocoDebugTestReport.xml

  instrumentation-tests:
    name: Instrumentation tests
    strategy:
      matrix:
        api-level: [ 33 ]
        target: [ google_apis ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
      - run: docker-compose -f docker/docker-compose-ci.yml up --build -d
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          ram-size: 4096M
          emulator-boot-timeout: 12000
          disable-animations: true
          emulator-build: 6061023
          script: ./gradlew yorkie:connectedCheck
      - uses: actions/upload-artifact@v3
        with:
          name: android-test-artifact
          path: yorkie/build/reports/coverage/androidTest/debug/connected/report.xml

  codecov:
    name: Codecov
    needs: [ unit-tests, instrumentation-tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: false
